import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";

const pfDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: [ '400', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
      className={`${pfDisplay.className} flex antialiased bg-bg-dark font-bold text-fg max-h-screen`}
      >
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
